# Mod basic info
mod_id=maid_restaurant_business
mod_name=Maid Restaurant: Now Open
mod_version=0.2.1
mod_group_id=com.icewolf.maidrestaurant.business
mod_authors=IceWolf
mod_license=MIT
mod_description=Touhou Little Maid x Maid Restaurant x Order to Cook integration addon for automated restaurant management.

# NeoForge version
neo_version=21.1.74

# Minecraft version
minecraft_version=1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
